# Generated by Django 4.2.6 on 2023-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_seq', models.CharField(max_length=50, null=True)),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('topic_text', models.TextField(null=True)),
                ('topic_task', models.TextField(null=True)),
            ],
        ),
    ]
